---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

# 12.1 
- Nathan: I've done all the prereqs, and I have experience with Git.
- Colin: I did the prereqs from chapter 7 on as I don't have previous experience with Git.
- Sebastian: I had to follow chapter 7 since this is my first time using git.
- Kenzie: I am familiar with Git.
# 12.2
- Nathan: Instead of creating a new repo, I referenced the group repo that was already made.
- Colin: 
- Sebastian: I used the lab group repo
- Kenzie: I used the pre-made reop
# 12.3
- Nathan: I cloned the project using RStudio, I manually adjusted the project directory. Now the project is displaying in RStudio
- Colin: 
- Sebastian: I cloned the project in Rstudio without issue. I created a new folder for labs in order to save the project there. 
- Kenzie: It took me a couple minutes, but I cloned the project in RStudio.
# 12.4
- Nathan: I committed changes locally, first it said there was no changes, I realized I hadn't saved my changes to the Rmd file.
- Colin: 
- Sebastian: I committed the changes after saving the changes for the README.rmd.
- Kenzie: I committed the changes. I had to use the terminal and save the project for it to work.
# 12.5
- Nathan: I pushed my changes to the remote. At first there was merge conflicts, but pulling down the changes resolved them automatically.
- Colin: 
- Sebastian: I had no issue pushing the changes.
- Kenzie: I had no trouble pushing the changes.
# 12.6
- Nathan: After refreshing the page, the Rmd file updated to reflect my changes.
- Colin: 
- Sebastian: The Rmd file was updated after reloading.
- Kenzie: I saw the changes in the file after I reloaded the page.
